name= input("What's your name? ")
animal= input("What's your favorite animal? Type it in lowercase. ")
insect= input("What's your least favorite insect? Type it in lowercase. ")
action= input("Enter an action verb that ends in 'ing'. Type it in lowercase. ")
adjective= input("Enter an adjective. Type it in lowercase. ")
place= input("What's a country you have never been to before? ")
bodyPart= input("Enter a body part. Type it in lowercase. ")
place2= input ("Enter a proper noun (any location). ")
feeling= input ("How do you feel right now? Type it in lowercase. ")
noun1= input ("Enter a plural noun. Type it in lowercase. ")
noun2= input ("Enter another plural noun. Type it in lowercase. ")
print (name + " goes to the farm to visit her uncle. He loves growing " + noun1 + " and " + noun2 + ". Additionally, " + name + " notices a lot of animals in the farm.")
print ("For example, " + name + " sees a small " + animal + " that is " + action + ".")
print ("Then, " + name + " notices a " + adjective + " " + insect + ".")
print ("Since she hates that insect, she runs away to " + place + ".")
print ("She falls while running and lands on her " + bodyPart + ".")
print ("Her uncle hears her screaming and runs towards her. He brings her to " + place2 + ".")
print ("After a long nap at " + place2 + ", she feels " + feeling + ".")
print ("The End.")
       

